### ISSUE TITLE
python 3.7.4  on windows

### ISSUE THREAD

**Issue by cumulus13** [DanySK/torrent2magnet#2]
Traceback (most recent call last):
  File "D:\PROJECTS\torrent2magnet\torrent2magnet.py", line 19, in <module>
    magnet = make_magnet_from_file(sys.argv[1])
  File "D:\PROJECTS\torrent2magnet\torrent2magnet.py", line 16, in make_magnet_from_file
    + '&xl=' + str(metadata[b'info'][b'length'])
KeyError: b'length'

**Comment by cumulus13** [comment]
> Traceback (most recent call last):
> File "D:\PROJECTS\torrent2magnet\torrent2magnet.py", line 19, in
> magnet = make_magnet_from_file(sys.argv[1])
> File "D:\PROJECTS\torrent2magnet\torrent2magnet.py", line 16, in make_magnet_from_file
> + '&xl=' + str(metadata[b'info'][b'length'])
> KeyError: b'length'

it can be:

return 'magnet:?'\
             + 'xt=urn:btih:' + b32hash\
             + '&dn=' + metadata[b'info'][b'name'].decode()\
             + '&tr=' + metadata[b'announce'].decode()\
             + '&xl=' + str(metadata[b'info'][b'piece length'])

**Comment by cumulus13** [comment]
return 'magnet:?'\
             + 'xt=urn:btih:' + b32hash\
             + '&dn=' + metadata[b'info'][b'name'].decode()\
             + '&tr=' + metadata[b'announce'].decode()\
             + '&xl=' + str(metadata[b'info'][b'piece length'])

**Comment by DanySK** [comment]
It might, I do not have a Windows installation where to test. Can you provide the original torrent? I might find some time and set up a multiplatform CI process
